server:
  port: 8080
spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.example-spring
      routing-key:
        producer: rk.producer.example-spring 
      deadletter:
         producer: dl.producer.example-spring 
      parkinglot:
         producer: pl.producer.example-spring
    listener:
      time-retry: 00 00 10 * * *    


